"""Add status and make faces_detected nullable

Revision ID: 2236a43e3193
Revises: cd87d50a5015
Create Date: 2026-07-01 09:49:54.982614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2236a43e3193'
down_revision: Union[str, None] = 'cd87d50a5015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_analysis', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('image_analysis', 'faces_detected',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image_analysis', 'faces_detected',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('image_analysis', 'status')
    # ### end Alembic commands ###
