"""Criando banco estruturado

Revision ID: cd87d50a5015
Revises: 
Create Date: 2026-07-01 09:00:33.064902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd87d50a5015'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_analysis', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'image_analysis', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image_analysis', type_='foreignkey')
    op.drop_column('image_analysis', 'user_id')
    # ### end Alembic commands ###
